config/routes.rb
Rails.application.routes.draw do
  resource :sessions, only: [:new, :create, :destroy]
  devise_for :managers
  root "posts#index"
  get "/posts/new" => "posts#new"
  get "/posts/:id" => "posts#show"
  post "/posts" => "posts#create"
  get "/posts/:id/edit" => "posts#edit"
  post "/posts/:id/update" => "posts#update"
  post "/posts/:id/destroy" => "posts#destroy"
  get "/posts" => "posts#list"

  get "/users/index" => "users#index"
  get "/users/:id" => "users#show"
  get "/signup" => "users#new"
  post "/users/create" => "users#create"
  post "/users/:id/update" => "users#update"
  get "/users/:id/edit" => "users#edit"
  get "/users/:id/likes" => "users#likes"
  get "/users" => "users#list"

  get "/login" => "users#login_form"
  post "/login" => "users#login"
  post "/logout" => "users#logout"

  post "/likes/:post_id/create" => "likes#create"
  post "/likes/:post_id/destroy" => "likes#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/create_posts_tags_table.rb
class CreatePostsTagsTable < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :create_posts_tags_tables
  has_many :tags, through: :create_posts_tags_tables
  validates :content, presence: true
  validates :user_id, presence: true
  default_scope -> { order(created_at: :desc) }

  def user
    return User.find_by(id: self.user_id)
  end

  def getUserName
    return User.joins(:posts).select("users.name")
  end

  def self.search(search)
    if search
      Post.where(['title like ?', "%#{search}%"])
    else
      Post.all
    end
  end

  def save_posts(savepost_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - savepost_tags
    new_tags = savepost_tags - current_tags

    # Create new taggings:
    new_tags.each do |new_name|
      post_tag = Tag.find_or_create_by(name:new_name)
      self.tags << post_tag
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  # has_and_belongs_to_many :posts
  has_many :posts, through: :create_posts_tags_tables
  has_many :create_posts_tags_tables
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  validates :name, {presence: true}
  validates :email, {presence: true, uniqueness: true}
  has_secure_password

  def posts
    return Post.where(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :set_current_user

  # def set_current_user
  #   @current_user = User.find_by(id: session[:user_id])
  # end

  # def authenticate_user
  #   if @current_user == nil
  #     flash[:notice] = "ログインが必要です"
  #     redirect_to("/login")
  #   end
  # end

  # def forbid_login_user
  #   if @current_user
  #     flash[:notice] = "すでにログインしています"
  #     redirect_to("/posts/index")
  #   end
  # end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  # before_action :authenticate_user


  def create
    @like = Like.new(
      user_id: @current_user.id,
      post_id: params[:post_id]
    )
    @like.save
    redirect_to("/posts/#{params[:post_id]}")
  end

  def destroy
    @like = Like.find_by(user_id: @current_user.id, post_id: params[:post_id])
    @like.destroy
    redirect_to("/posts/#{params[:post_id]}")
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :authenticate_user
  # before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}

  def index
    @posts = Post.search(params[:search])
    @tags = [];
    if @posts.blank?
      @searchResult = false;
      return;
    end
    @searchResult = true
  end

  def show
    @post = Post.find_by(id:params[:id])
    @user = @post.user
    @likes_count = Like.where(post_id: @post.id).count
  end

  def new
    @post = Post.new
  end

  def create
    if params[:post][:image_name].present?
      @post = Post.new(
        title: params[:post][:title],
        content: params[:post][:content],
        image_name: params[:post][:image_name].original_filename,
        user_id: current_manager.id
      )
    else
      @post = Post.new(
        title: params[:post][:title],
        content: params[:post][:content],
        image_name: "no-image.png",
      )
    end

    if params[:post][:image_name].present?
      output_path = Rails.root.join('public/images', params[:post][:image_name].original_filename)
      File.open(output_path, 'w+b') do |fp|
        fp.write(params["post"]["image_name"].read)
      end
    end
   

    tag_list = params[:tag_name].split(",")
    if @post.save
      @post.save_posts(tag_list)
    end
    redirect_to root_path
  end

  def edit
    @post = Post.find_by(id:params[:id])
    @tags = [];
  end

  def update
    @post = Post.find_by(id:params[:id])
    @post.title = params[:title]
    @post.content = params[:content]
    @post.save
    redirect_to root_path
  end

  def destroy
    @post = Post.find_by(id:params[:id])
    @post.destroy
    @post.save
    redirect_to root_path
  end

  def ensure_correct_user
    @post = Post.find_by(id: params[:id])
    if @post.user_id != @current_user.id
      flash[:notice] = "権限がありません"
      redirect_to("/posts/index")
    end
  end

  def list
    @posts = Post.all
    render json: @posts
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :authenticate_manager, {only: [:edit, :update, :index, :show]}
  # before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  # before_action :ensure_correct_user, {only: [:edit, :update]}
  # protect_from_forgery :except => [:login]

  def index
    @users = User.all
  end

  def list
    @users = User.all
    render json: @users
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(
      name: params[:name],
      email: params[:email],
      image_name: "default_user.png",
      password: params[:password]
    )
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to("/users/#{@user.id}")
    else
      render("users/new")
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.email = params[:email]

    if params[:image]
      @user.image_name = "#{@user.id}.jpg"
      image = params[:image]
      File.binwrite("public/images/user_images/#{@user.image_name}", image.read)
    end

    if @user.save
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to("/users/#{@user.id}")
    else
      render("users/edit")
    end
  end

  # def login_form
  # end

  # def login
  #   @user = User.find_by(email: params[:email])
  #   if @user && @user.authenticate(params[:password])
  #     session[:user_id] = @user.id
  #     flash[:notice] = "ログインしました"
  #     redirect_to("/")
  #   else
  #     @error_message = "メールアドレスまたはパスワードが間違っています。"
  #     @email = params[:email]
  #     @password = params[:password]
  #     render("users/login_form")
  #   end
  # end

  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/login")
  end

  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to users_index_url
    end
  end

  def likes
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
<p><%= @name %></p>

app/views/layouts/_header.html.erb
<header class="header" id="header">
  <header-component :isSignIn="isSignIn"></header-component>
</header>

<script>
new Header({
  el: '#header',
  data: {
    isSignIn: <%= manager_signed_in? %>,
  }
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/styles/atelier-sulphurpool.dark.min.css">
    <!--<%= javascript_include_tag "application" %>>-->
    <%= javascript_include_tag "/javascripts/viewmodel/posts/index" %>
    <%= javascript_include_tag "/javascripts/viewmodel/posts/show" %>
    <%= javascript_include_tag "/javascripts/viewmodel/posts/edit" %>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <%= notice %>
    <div class='container'>
      <%= yield %>
    </div>
    <%= alert %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: {class: 'newPost'} do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </p>
  <%= f.submit("submit") %>
<% end %>

app/views/posts/edit.html.erb
<div id="postEdit">
  <edit-component :post="post" :token="authenticationToken"></edit-component>
</div>

<script>
  new PostEdit ({
    el: "#postEdit",
    created(){
      this.post["tags"] = this.tags;
    },
    data: {
      post: <%= raw @post.to_json %>,
      authenticationToken: '<%= form_authenticity_token %>',
      tags: <%= raw @post.tags.to_json %>
    }
  })
</script>

app/views/posts/index.html.erb
<div class="posts" id="vuePosts">
  <% @posts.each do |post| %>
    <% @tags.push(post.tags) %>
  <% end %>

  <post-component
    :post="post"
    v-for="post in posts"
    :is-sign-in="isSignIn"
    key="post.id">
  </post-component>

  <div v-if="!searchResult">
    <p>検索条件に合う記事は見つかりません。</p>
    <%= link_to "ブログトップへ", root_path %>
  </div>
</div>
<script>
new Posts({
  el: "#vuePosts",
  created(){
    for(let i = 0; i < this.posts.length; i++){
      this.posts[i]["tags"] = this.tags[i]
    }
  },
  data: {
    posts: <%= raw @posts.to_json %>,
    searchResult: <%= @searchResult %>,
    isSignIn: <%= manager_signed_in? %>,
    tags: <%= raw @tags.to_json %>
  }
})
</script>

app/views/posts/new.html.erb
<% @post.errors.full_messages.each do |message| %>
  <div class="form-error">
    <%= message %>
  </div>
<% end %>

<div class="postNew">
  <new-component :post="post" :token="authenticationToken"></new-component>
</div>

<%= javascript_include_tag "/javascripts/viewmodel/posts/new" %>

<script>
new PostNew({
  el: '.postNew',
  data:{
    post: <%= raw @post.to_json %>,
    authenticationToken: '<%= form_authenticity_token %>'
  }
})
</script>

app/views/posts/show.html.erb
<div class="post" id="PostShow">
  <show-component :post="post"></show-component>
</div>
<script>
new PostShow({
  el : "#PostShow",
  data: {
    post: <%= raw @post.to_json %>
  }
})
</script>

app/views/users/edit.html.erb
<%= form_tag("/users/#{@user.id}/update", {multipart:true}) do %>
  <label for='title'>ユーザー名</label>
  <p><input type='text' name="name" value="<%= @user.name %>"></p>
  <label for='content'>メールアドレス</label>
  <p><textarea name='email' id='' cols='30' rows='10'>
    <%= @user.email %>
  </textarea></p>
  <p><input type='file' name="image"></p>
  <input type="submit" value="保存">
<% end %>
<%= link_to "戻る", root_path %>

app/views/users/index.html.erb
<div id='main'>
  <ul>
    <user-list :user="user" v-for="(user, index) in users" key="index"></user-list>
  </ul>
</div>
<%= javascript_include_tag "/javascripts/viewmodel/users/index" %>

app/views/users/likes.html.erb
<!-- 指定されたコードを貼り付けてください -->
<div class="main user-show">
  <div class="container">
    <div class="user">
      <p><img src="<%= "/images/user_images/#{@user.image_name}" %>"></p>
      <h2><%= @user.name %></h2>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
        <%= link_to("編集", "/users/#{@user.id}/edit") %>
      <% end %>
    </div>
    
    <ul class="user-tabs">
      <li><%= link_to("投稿", "/users/#{@user.id}") %></li>
      <li class="active"><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
    </ul>
    
    <!-- 変数@likesに対してeach文を用いてください -->
   <% @likes.each do |like| %>
      <!-- 変数postを定義してください -->
      <% post = Post.find_by(id:like.post_id) %>
      
      <div class="posts-index-item">
        <div class="post-left">
          <p><img src="<%= "/images/user_images/#{post.user.image_name}" %>"></p>
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to(post.user.name, "/users/#{post.user.id}") %>
          </div>
          <%= link_to(post.content, "/posts/#{post.id}") %>
        </div>
      </div>
    <!-- each文のendを追加してください -->
    <% end %>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="main users-new" id="LoginForm">
  <login-component :email="email" :password="password"></login-component>
</div>
<%= javascript_include_tag "/javascripts/viewmodel/users/login" %>


<script>
new Login({
  el: '#LoginForm',
  data:{
    error_message: '<% @error_message %>',
    email: '<% @email %>',
    password: '<% @password %>'
  }
})
</script>

app/views/users/new.html.erb
<p>ユーザー名</p>
<% @user.errors.full_messages.each do |message| %>
  <div class="form-error">
    <%= message %>
  </div>
 <% end %>
<%= form_tag("/users/create") do %>
  <input type="text" name="name">
  <p>メールアドレス</p>
  <p><input type="text" name="email"></p>
  <p><input type="file" name="image"></p>
  <p><input type="password" name="password" value="<%= @user.password %>"></p>
  <input type="submit" value="新規登録">
<% end %>
<%= link_to "戻る", root_path %>

app/views/users/show.html.erb
<div id="fuga">
  <user-profile-component :user="user"></user-profile-component>
</div>
<%= javascript_include_tag "/javascripts/viewmodel/users/show" %>
<script>
  new UserProfile({
    el: "#fuga",
    data: {
      user: <%= raw @user.to_json %>
    }
  })
</script>